name: oxlint

on:
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 20
      - name: Install dependencies
        run: pnpm install
      - name: run oxlint
        run: pnpm lint
